<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jannah" name="com.stc.testcases.Sprint1Cases" tests="12" failures="0" timestamp="23 Jun 2019 13:20:33 GMT" time="310.749" errors="1">
  <testcase name="InvalidMobileNumErrorMsg" time="9.894" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="notifyMeGuestUser" time="32.883" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="checkoutWithoutEmailMobileVerification" time="79.820" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="verifyTermsAndConditionDefaultState" time="19.675" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="verifyOffersAndAlertsDefaultState" time="2.766" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="duplicateMobileNumberError" time="10.341" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="notifyMeTwoCities" time="72.539" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="notifyMeRegisteredUser" time="50.427" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="duplicateEmailError" time="9.746" classname="com.stc.testcases.Sprint1Cases">
    <error type="java.lang.AssertionError" message="Error Messge appears correctly when the user tries to register with Email that is already used  expected [User Already Exist. Please Login] but found [Invalid mobile number! Mobile number should start with 5 and have 9 digits]">
      <![CDATA[java.lang.AssertionError: Error Messge appears correctly when the user tries to register with Email that is already used  expected [User Already Exist. Please Login] but found [Invalid mobile number! Mobile number should start with 5 and have 9 digits]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.stc.base.TestUtils.verifyDuplicateEmailErrorMessage(TestUtils.java:549)
	at com.stc.testcases.Sprint1Cases.duplicateEmailError(Sprint1Cases.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- duplicateEmailError -->
  <testcase name="smallPasswordErrorMsg" time="10.504" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="OffersAndAlertsDeselect" time="2.407" classname="com.stc.testcases.Sprint1Cases"/>
  <testcase name="InvalidEmailErrorMsg" time="9.747" classname="com.stc.testcases.Sprint1Cases"/>
</testsuite> <!-- com.stc.testcases.Sprint1Cases -->
